---
'Shell host':
  address: 'insomnia247.nl'
  services:
    FTP:
      type: tcp
      port: 21
      ssl: false
      expect: '220 ProFTPD'
    SSH:
      type: tcp
      port: 22
      ssl: false
      expect: 'SSH-2.0-OpenSSH'
    SMTP:
      type: tcp
      port: 25
      ssl: false
      expect: '220 gateway02.insomnia247.nl ESMTP Postfix'
    HTTP:
      type: http
      port: 80
      ssl: false
      get: '/'
      expect: '302 Found'
    HTTPS:
      type: http
      port: 443
      ssl: true
      get: '/'
      vhost: 'www.insomnia247.nl'
      expect: 'News - Insomnia 24/7'
    IMAPS:
      type: tcp
      port: 993
      ssl: true
      expect: 'Dovecot (Debian) ready'
    POP3S:
      type: tcp
      port: 995
      ssl: true
      expect: 'Dovecot (Debian) ready'
    'Sign-up page':
      type: http
      port: 443
      ssl: true
      get: '/'
      vhost: 'signup.insomnia247.nl'
      expect: 'Welcome to the Insomnia 24/7 shells signup'
    'Web shell':
      type: http
      port: 443
      ssl: true
      get: '/'
      vhost: 'shell.insomnia247.nl'
      expect: 'ShellInABox'
'Gitlab server':
  address: 'git.insomnia247.nl'
  services:
    SSH:
      type: tcp
      port: 33
      ssl: false
      expect: 'SSH-2.0-OpenSSH'
    Web interface:
      type: http
      port: 443
      ssl: true
      get: '/users/sign_in'
      expect: 'GitLab Community Edition'
'Nextcloud':
  address: 'nextcloud.insomnia247.nl'
  services:
    HTTPS:
      type: http
      port: 443
      ssl: true
      get: '/index.php/login'
      expect: 'Nextcloud'
    WebDAV:
      type: http
      port: 443
      ssl: true
      get: '/remote.php/webdav'
      expect: '401 Unauthorized'
'Wiki server':
  address: 'wiki.insomnia247.nl'
  services:
    HTTPS:
      type: http
      port: 443
      ssl: true
      get: '/wiki/Main_Page'
      expect: 'Main Page'
'VM host':
  address: 'vm.insomnia247.nl'
  services:
    HTTPS:
      type: http
      port: 443
      ssl: true
      get: '/'
      expect: 'Proxmox Virtual Environment'
'Wargames':
  address: 'wargames.insomnia247.nl'
  services:
    HTTPS:
      type: http
      port: 443
      ssl: true
      get: '/'
      expect: 'Insomnia 24/7 wargames'
    Target 1:
      type: tcp
      port: 10131
      ssl: false
      expect: 'SSH-2.0-OpenSSH'
    Target 2:
      type: tcp
      port: 10132
      ssl: false
      expect: 'SSH-2.0-OpenSSH'
    Target 3:
      type: tcp
      port: 10133
      ssl: false
      expect: 'SSH-2.0-OpenSSH'
